node{
	def mvnHome
	def dockerHome
	stage('Checkout'){
		git url: 'file://E:\LTI\workspace\discovery-server', branch: 'master'
		mvnHome = tool 'Local Maven'
		dockerHome = tool 'MyDocker'
	}
	
	stage('Build'){
		bat(/"${mvnHome}\bin\mvn" clean package)
	}
	
	stage('DockerImage'){
		bat(/"${dockerHome}\resources\bin\docker" build -t discovery-server:lti .)
	}
	
	stage('Trigger Next'){
		build job : 'lti-api-gateway-job'
	}
}